### ISSUE TITLE
Uplift to core

### ISSUE THREAD

**Issue by clokep** [bstreiff/unread-badge#1]
"The Mozilla core supports setting the overlay, but the bug for actually making Thunderbird do so has languished for about four years. Sigh."

Any reason you haven't put a patch on the bug yourself? Looking over your code it seems like it is already pretty polished.

**Comment by bstreiff** [comment]
I just learned today that, thanks to the generous work of Ping Chen, the bulk of this extension has been [integrated into core](https://hg.mozilla.org/comm-central/file/tip/mailnews/base/src/WinUnreadBadge.jsm) as part of [bugzilla bug 715799](https://bugzilla.mozilla.org/show_bug.cgi?id=715799#c30), and should, as far as I can tell, be in Thunderbird 91.

As such, I will freeze and archive this repo when Thunderbird 91 releases, and any further bugs or changes should be filed with the upstream Thunderbird team.

Thank you to everyone who has used this extension, contributed bugfixes, and put up with my glacial release cycles after all these years. ❤

**Comment by homo-programmatis** [comment]
Congratulations and thanks for your hard work!
