### ISSUE TITLE
Update published addon

### ISSUE THREAD

**Issue by homo-programmatis** [bstreiff/unread-badge#12]
https://addons.mozilla.org/en-US/thunderbird/addon/unread-badge/

Also, I suggest the following changes to this repo's description:
1) Make it clear that bug is no longer important
2) Add reference to thunderbird's addon page

**Comment by bstreiff** [comment]
v1.2 (with compatibility up to 60.0beta2) is presently sitting in the AMO review queue.

**Comment by homo-programmatis** [comment]
Perfect!
And really, thanks for your work again!

**Comment by bstreiff** [comment]
Thank you for discovering a workaround for the showstopper issue that had led me to give up on it before. :)

https://addons.mozilla.org/en-US/thunderbird/addon/unread-badge/ is live with version 1.2.20180408.
