### ISSUE TITLE
messages in gmail "Important" folder are double-counted

### ISSUE THREAD

**Issue by gkpdex** [bstreiff/unread-badge#13]
Hi,

I use gmail and the badge count adds up the inbox, all mail and important. Is there anyway just to show the inbox total?

Thanks
gkpdex

**Comment by bstreiff** [comment]
Hm. It doesn't appear that the "Important" folder is known to be a special folder by Thunderbird. If so, it may be difficult to automatically deduce that we shouldn't double-count unread items there-- the existing unread-count enumeration code is based around which folders TB knows as being special.

Having some sort of per-folder configuration may be necessary to handle cases like these...

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
