### ISSUE TITLE
Compatibility with Thunderbird 60

### ISSUE THREAD

**Issue by Big--Mike** [bstreiff/unread-badge#16]
Hi,

Unread Badge doesn't work with Thunderbird 60.
I get the following error in the console:
![image](https://user-images.githubusercontent.com/4572946/44297326-c01f3200-a2cf-11e8-9f58-f4f86f4b6186.png)

Could you please adapt your addon for Thunderbird 60

**Comment by foguetes** [comment]
It still doesn't work, even though Thunderbird doesn't alert for that fact.

**Comment by homo-programmatis** [comment]
I fixed it; pull request: https://github.com/bstreiff/unread-badge/pull/17

**Comment by bstreiff** [comment]
PR 17 is in and an updated build (1.2.20181207) is in the addons.thunderbird.net review queue.
