### ISSUE TITLE
Permit to exclude folders

### ISSUE THREAD

**Issue by g4b0** [bstreiff/unread-badge#20]
It would be nice to be able to exclude certain folders from the total message count.

**Comment by tooomm** [comment]
Also, excluding certain accounts would be awesome and very helpful.

**Comment by CountCount** [comment]
I second both suggestions, but I am keen especially on the first one. I am not sure if it would be easier, to add an option to only count the inbox itself.

Right now, the add-on is somewhat useless for me as I receive a lot of automated mails which are properly filtered away into subfolders. I would need a badge that only shows unread messages in my inboxes.

**Comment by bstreiff** [comment]
@CountCount an "only count inboxes" checkbox already exists in the add-on's options.

![image](https://user-images.githubusercontent.com/444845/97711382-0a44f600-1a8b-11eb-8b0a-a5aa7bc35faa.png)

**Comment by CountCount** [comment]
Thanks, I totally missed that option.

**Comment by emergy** [comment]
> @CountCount - флажок «только подсчитывать входящие» уже существует в параметрах надстройки.
> 
> ![образ](https://user-images.githubusercontent.com/444845/97711382-0a44f600-1a8b-11eb-8b0a-a5aa7bc35faa.png)

Is this in version 2.0.0 of the extension? I can't find something

**Comment by UTANdev** [comment]
Add my vote to being able to select which accounts are included in the displayed count. I only want unread emails from a specific business account and my personal inbox keeps Spamming the counter. Thanks for a great add-on.

**Comment by pbarquei** [comment]
+1 for being able to select which accounts to include in the displayed count. Anyway, thanks for the add-on.

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
