### ISSUE TITLE
Not compatible with Thunderbird 68

### ISSUE THREAD

**Issue by jeichberger** [bstreiff/unread-badge#22]
Thunderbird 68 complaings with the message "Unread Badge is incompatible with Thunderbird 68.0."

Thanks a lot for this extension, it brings a fundamental feature to Thunderbird that most other apps have built-in. It would be great if it would work with current Thunderbird 68 😉

**Comment by bstreiff** [comment]
Fixed in [v2.0.0](https://github.com/bstreiff/unread-badge/releases/tag/v2.0.0), which is now in the Thunderbird Addons review queue.
