### ISSUE TITLE
How to access the settings in TB 68? 

### ISSUE THREAD

**Issue by tooomm** [bstreiff/unread-badge#23]
Where can I access the setting to count only the primary inboxes of each account?

Using the new version 2.0

**Comment by bstreiff** [comment]
Look under the "Add-ons" option in the hamburger menu.

![addon_options](https://user-images.githubusercontent.com/444845/64986966-c7778d00-d88d-11e9-9867-182ab36d656a.png)

**Comment by tooomm** [comment]
Thanks a lot for the helpful explanation.

That was new to me... it works differently in Firefox. :)
