### ISSUE TITLE
Compatibility with Thunderbird 78

### ISSUE THREAD

**Issue by stefangabos** [bstreiff/unread-badge#26]
Please make it work with Thunderbird 78
Thank you!

**Comment by SergeyMaltsev** [comment]
+1 Vote for this!
Doesn't work with Thunderbird 80.0beta also.

**Comment by olausman** [comment]
+1 Vote for this!

**Comment by ManuDevil** [comment]
Your addon was very useful. Could you please update ? Thank you for your work, anyway.

**Comment by homo-programmatis** [comment]
In Thunderbird 78, they stopped support for old addon API and demand addons to be rewritten with new API:
https://developer.thunderbird.net/add-ons/updating/tb78

**Comment by Stefan-Ilic** [comment]
Hi @homo-programmatis,

do you by any chance know if that "only" means the extension has to be re-written or that it is impossible to change the taskbar icon with the new APIs?

**Comment by homo-programmatis** [comment]
My understanding (which is not exactly reliable) is that it won't be possible with new API, but it's still possible to continue using old API for a while if it's moved into "Experiment" code as described in the article.

**Comment by bstreiff** [comment]
Using [the BootstrapLoader shim](https://github.com/thundernest/addon-developer-support/wiki/Using-the-BootstrapLoader-API-to-convert-a-Legacy-Bootstrap-WebExtension-into-a-MailExtension-for-Thunderbird-78) got me to the point of being able to load the extension in TB78. My current snag is that the `nsIXULWindow` interface seems to be gone, which we [currently use to retrieve an `nsIDocShell`](https://github.com/bstreiff/unread-badge/blob/master/src/bootstrap.js#L352) from which we can get the overlay icon controller, and I haven't yet found an equivalent way to get an appropriate `nsIDocShell`.

**Comment by SyntevoAlex** [comment]
Please push your current code to a branch, and I will try to find a solution.

**Comment by bstreiff** [comment]
> Please push your current code to a branch, and I will try to find a solution.

https://github.com/bstreiff/unread-badge/tree/dev/bstreiff/tb78

**Comment by homo-programmatis** [comment]
Browsing Firefox code, I found two candidate snippets. Can't test them at the moment.
1. `aWindow.browsingContext.topChromeWindow.docShell`
2. `Cc["@mozilla.org/appshell/window-mediator;1"].getService(Ci.nsIWindowMediator).getMostRecentWindow("navigator:browser").docShell`

**Comment by homo-programmatis** [comment]
This works to get a `docShell`:

    Cc["@mozilla.org/appshell/window-mediator;1"]
      .getService(Ci.nsIWindowMediator)
      .getMostRecentBrowserWindow()
      .docShell

However, now there's again the problem where using `imgIContainer` returns `NS_ERROR_NOT_AVAILABLE` because the image is not decoded. So it seems I need to find a new workaround for `forceImgIContainerDecode`...

**Comment by homo-programmatis** [comment]
During my debugging I also came across this class which has icon sizes:
`Cc["@mozilla.org/windows-ui-utils;1"].getService(Ci.nsIWindowsUIUtils).systemSmallIconSize`

DPI can possibly be obtained from `window.windowUtils.screenPixelsPerCSSPixel` or `window.windowUtils.displayDPI`.

These together could replace registry reading in `overlayIconSize()`

**Comment by stefangabos** [comment]
thanks for the release! seems to be working

**Comment by bstreiff** [comment]
[3.0.0](https://github.com/bstreiff/unread-badge/releases/tag/v3.0.0) has been submitted to addons.thunderbird.net and is currently in the review queue (or it can be grabbed from the github releases page)
