### ISSUE TITLE
Add support for Linux

### ISSUE THREAD

**Issue by k-kirill** [bstreiff/unread-badge#29]
Could you please consider implementing Linux support by using the following low level DBus API: https://wiki.ubuntu.com/Unity/LauncherAPI? I do not know if emitting the correspondent DBus signal when the number of unread messages changes is hard to code, but it is basically all what is needed. Applications like Telegram support it or the following mpv plugin: https://github.com/mrlotfi/mpv-libunity.
Thanks!

**Comment by bstreiff** [comment]
renaming: this seems to be an API specific to Ubuntu Unity, and not generally "Linux support".

I'm not aware of any Thunderbird-exposed APIs for directly sending DBus messages; the closest I could find is https://github.com/janoliver/thunderbird-dbus-sender, which uses a `nsIProcess` API for launching a python `dbus-sender.py` script to perform the DBus messaging. However, the future of Thunderbird addons is [MailExtensions](https://developer.thunderbird.net/add-ons/mailextensions), and while we could interface through such things through "Experimental APIs", it also seems likely that such things are going to be closed off from us in the future... so I'm a bit hesitant to commit to supporting that now.

**Comment by k-kirill** [comment]
At least KDE Plasma and Dash to Dock GNOME extension support Unity launcher API, that's why I used Linux as it is the only more or less standard way I know to display badges in Linux.
And thank you for considering it.

**Comment by k-kirill** [comment]
@bstreiff could you please check if the extension could run an external command with the actual number instead of 13 in the following example?
```
gdbus emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update "application://thunderbird.desktop" "{'count': <int64 13>, 'count-visible': <true>}"
```

**Comment by vinzv** [comment]
I just tried with Plasma (on openSUSE) and it works, basically: 
![grafik](https://user-images.githubusercontent.com/74432/98816785-77607000-2429-11eb-95c5-a06e3eab1666.png)
(of course the hard coded count is incorrect)

**Comment by Apflkuacha** [comment]
Wuhuu, just executing a single line in terminal will have this result, I'm using Manjaro with KDE Plasma. Would be glad to see it implemented soon :) 
![image](https://user-images.githubusercontent.com/31316050/108189388-f7753080-7110-11eb-9ef5-541a3bbd1a9f.png)

**Comment by k-kirill** [comment]
@Apflkuacha, I guess you can try this add-on then as it supports a custom notification command: https://addons.thunderbird.net/en-us/thunderbird/addon/mailbox-alert/

**Comment by Apflkuacha** [comment]
Yeah - i also saw this Addon.. It kind of works - if I receive an Email the code above could be executed and the count 1 is shown in tray. After reading the mail the counter is still on 1, there is no possibility to execute a command if the mails are read

**Comment by barolo** [comment]
How to modify that command to get the actual count?

**Comment by Apflkuacha** [comment]
I tried to implement it, but I couldn't get my own built plugin running in Thunderbird. None of my console logs were visible in the Addon-Debugging Tab.. So someone with more expirience in Thunderbird-Addons should implement it.
Here my Code I've got so far to execute the command. Not sure with the parameters, though. This should be in the updateOverlayIcon function: 

    var executable_name = "/bin/gdbus";
    var exec = new FileUtils.File( executable_name )
    if (!exec.exists()) {
        console.log("Command " + executable_name + " not found!");
    } else {
        console.log("Execute " + executable_name);
        var pr = Cc["@mozilla.org/process/util;1"].createInstance(Components.interfaces.nsIProcess);
        var res1 = pr.init(exec);
        //var parameters = ["emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update \"application://thunderbird.desktop\" \"{'count': <int64 0>, 'count-visible': <false>}\""];
        var parameters = ["emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update \"application://thunderbird.desktop\" \"{'count': <int64 " + messageCount + ">, 'count-visible': <true>}\""];
        pr.runw(false, parameters, parameters.length);
        console.log("Command run, exitval: " + pr.exitValue);
    }

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
