### ISSUE TITLE
Rotate new message counts instead of showing the sum total

### ISSUE THREAD

**Issue by nvx2004** [bstreiff/unread-badge#31]
Would it please be possible to rotate the numbers of unread messages in all the inboxes instead of showing the sum total? A nice option would also be the possibility to colour-code the accounts and, therefore, being able to distinguish just by looking at the overlay colour which account contains how many unread messages.

Example 1:
* There are two mailboxes, A and B.
* Inbox of A contains 1 unread message, inbox of B 2 unread messages.
--> The overlay shows "1", then after 1--2 seconds switches to showing "2", then after 1--2 seconds switches back to showing "1", and so on.

Example 2:
* There are two mailboxes, A and B.
* Inbox of A contains no unread messages, inbox of B 1 unread message.
--> The overlay simply shows "1".

Thanks.

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
