### ISSUE TITLE
Request: support small icons mode (Windows)

### ISSUE THREAD

**Issue by JackSlaterIV** [bstreiff/unread-badge#32]
I have the Windows taskbar option "Use small taskbar icons" enabled, and the badge is not showing.
Could you make this extension work in this case?
Thanks

**Comment by emilkholod** [comment]
Found this: https://github.com/nwjs/nw.js/issues/3755. It seems that it doesn't work

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
