### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by Flabbergash** [bstreiff/unread-badge#33]
Hey,

For some reason, the counter is doubling for every email - for example - if I have 5 unread emails, the counter shows 10, I can't figure out why!

**Comment by SyntevoAlex** [comment]
See https://github.com/bstreiff/unread-badge/issues/15

**Comment by Flabbergash** [comment]
> See #15

Thanks - but I only have 1 account active?

**Comment by SyntevoAlex** [comment]
In that case, I don't know. Let's wait for others to take their attempt at solving.

**Comment by Flabbergash** [comment]
Thanks dude!

**Comment by vmancebo** [comment]
I had this same problem. What happened to me is that the count considered inbox e-mail as well as other folders such as the "Important" folder. 
So, if I had one new e-mail in the inbox that happened to be classified as "Important", the counter understand that there is one unopen e-mail in the inbox folder and another in the "Important" folder. 

Go to Add-on -> Unread Badge -> Options -> Only count inboxes abd mark this item to solve the double count on this particular case.

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
