### ISSUE TITLE
Request: Show unread badge in tray icon

### ISSUE THREAD

**Issue by tooomm** [bstreiff/unread-badge#34]
For users which use the new minimize to tray feature in TB 78 it would help a lot to see a unread badge in the tray icon in the lower right corner as well. Maybe not necessarily a badge the the complete number of unread messages like Telegram does for example, but only a red dot for better recognition at least?

It would be great to have a easy way to tell that a new mail arrived even when Thunderbird is minimized to the tray.

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
