### ISSUE TITLE
TB crashes after receiving new message

### ISSUE THREAD

**Issue by xs133** [bstreiff/unread-badge#35]
TB 78 is minimized in the Info Info Tray. After receiving a new message and then starting TB from the info tray, the program  **TB crashes** and has to be restarted.

If TB is only minimized, it is possible to continue working normally without a crash.

After **switching off** the unread-badge 3.00 extension, TB can be started from the infotray without any problems.

**Comment by cengizhan** [comment]
i also had the same problem. i have found that the culprit was this addon.

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
