### ISSUE TITLE
Unread count not showing in windows taskbar icon

### ISSUE THREAD

**Issue by f-brinkmann** [bstreiff/unread-badge#36]
The unread count got unreliable for me after the latest Thunderbird update. I can make it appear through somewhat random restarting Thunderbird and activating/deactivating Unread Badge.

I'm using
Windows 10
Thunderbird 78.7.1 (32-bit)
Unread Badge 3.0.0

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
