### ISSUE TITLE
Combined inbox unread count error

### ISSUE THREAD

**Issue by jenolan** [bstreiff/unread-badge#38]
I use a single inbound email folder what is happening for each message is that the count of emails is being incremented once per email account and again for the combined mail box.

In this case with three accounts + the actual inbox each email in the inbox counts as '4' instead of '1'

![2021-05-05](https://user-images.githubusercontent.com/1505228/117093134-73435880-ada3-11eb-8e4f-0259e21da3b4.png)

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
