### ISSUE TITLE
Unread subfolders of Thunderbird 91 are not counted

### ISSUE THREAD

**Issue by norvice74** [bstreiff/unread-badge#41]
[thunderbird 78]
Count correctly

[thunderbird 91]
Root in-box are counted.
Subfolders are not counted

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
