### ISSUE TITLE
Option to mimic tray icon

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [bstreiff/unread-badge#6]
Would it be feasible to have this (or a fork) do nothing more than mimic the tray icon, as Outlook does? That is, the program would show an envelope overlay when new mail arrives, and clear it again when you've deleted a message or marked one as read.

That would be one fewer tray icon required.

(I've looked at the code for the add-on itself, but I haven't a clue how to actually get the count in question. getNumNewMessages() worked for a few minutes (caused the overlay to appear and disappear in relation to the tray icon) but then stopped, and the Mozilla docs don't explain what it actually does.)

**Comment by bstreiff** [comment]
Closing all extant issues and pull requests in preparation for archival. Thunderbird 91 now includes much of this extension [as part of its core](https://hg.mozilla.org/comm-central/rev/be98a78846bd) and so development in this repo has stopped. Please address future issues/PRs to the Thunderbird team.
