### ISSUE TITLE
No overlay with Thunderbird 38.0.1

### ISSUE THREAD

**Issue by jbransen** [bstreiff/unread-badge#8]
I just updated my Thunderbird and now this addon has stopped working. I do not see an overlay anymore, the error console displays the following error:

`Error: NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsITaskbarOverlayIconController.setOverlayIcon]
Source file: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/<username>/AppData/Roaming/Thunderbird/Profiles/[...].default/extensions/unread-badge@streiff.net.xpi!/bootstrap.js
Line: 428`

I'm using a 32-bit version of Windows 7.

**Comment by dasmaetthes** [comment]
Same problem here with Windows 8.1 64 Bit.
Hope for fast fix, as now I often miss Mails.

**Comment by bstreiff** [comment]
I just got the update from 31.7.0 to 38.0.1, I see it too.

I'll see if I can figure out what's up... if Thunderbird removed the setOverlayIcon interface, that would be a bummer.

**Comment by bstreiff** [comment]
As far as I can tell I'm doing everything correctly, filed a bug to Mozilla for more assistance. https://bugzilla.mozilla.org/show_bug.cgi?id=1176448

**Comment by dasmaetthes** [comment]
There are some news about this bug?
There was a about but it didn't solved the problem the Add-On still doesn't work for me.

**Comment by bstreiff** [comment]
There's been no progress on the upstream Mozilla bug (1176448) regarding the setOverlayIcon interface being broken, and I unfortunately haven't had time to bisect and build Thunderbird between versions 35 and 36 to see what changeset broke it.

The only workaround I am aware of is to use a version earlier than Thunderbird 36.

**Comment by MaluNoPeleke** [comment]
That is not a good solution because of security fixes.
Lately there was a comment about this in the BugZilla entry. Maybe this will be fixed soon!?

**Comment by panique** [comment]
Hey guys, maybe this is relevant for the project: Windows 10 will introduce a new Application-to-OS-API in August 2016, allowing any application to send some kind of information to the taskbar representation. Looks like it's more than just integers :)

As Mozilla will probably need months or years to use the feature, this repo here might actually see a revival (or a fork?) in case the Win10 badge will not work out-of-the-box with Thunderbird.

![badge-notifications-windows-10-taskbar](https://cloud.githubusercontent.com/assets/156321/17126475/e5938d5c-52fd-11e6-9122-e041111b14c0.png)

Screenshot by http://windowsreport.com/windows-10-taskbar-badge-notifications/

FYI I've also forked the project to https://github.com/panique/thunderbird-unread-badge (for sure with full credit to Brandon), feel free to commit and fork.

**Comment by MaluNoPeleke** [comment]
Thanks for your effort @panique, that looks quite promising. 
Is it possible to make it work with Thunderbird 45.x as well?

**Comment by homo-programmatis** [comment]
The issue is fixed now and addon works with newest Thunderbird (52.7)

**Comment by jbransen** [comment]
Awesome!
